import time

from otari_agent.domain.evaluators import _segment_matches, _segments_match, evaluate_path
from otari_agent.domain.types import Outcome, PathEvidence, PathGate


def _gate(**overrides: object) -> PathGate:
    defaults: dict[str, object] = {
        "runs": ("pre_tool_use.edit_target", "stop.working_tree"),
        "id": "no-hand-edited-changelog",
        "enforcement": "required",
        "forbidden": ("CHANGELOG.md",),
        "message": "CHANGELOG.md is generated by git-cliff at release time.",
    }
    defaults.update(overrides)
    return PathGate(**defaults)  # type: ignore[arg-type]


def test_pass_when_no_forbidden_path_changed() -> None:
    result = evaluate_path(_gate(), PathEvidence(paths=("README.md", "src/gateway/cli.py")))
    assert result.outcome is Outcome.PASS
    assert not result.outcome.is_blocking


def test_fail_when_a_forbidden_path_changed() -> None:
    evidence = PathEvidence(paths=("CHANGELOG.md",))
    result = evaluate_path(_gate(), evidence)
    assert result.outcome is Outcome.FAIL
    assert result.outcome.is_blocking
    assert "CHANGELOG.md" in (result.detail or "")


def test_unknown_when_evidence_was_not_collected() -> None:
    result = evaluate_path(_gate(), None)
    assert result.outcome is Outcome.UNKNOWN
    assert result.outcome.is_blocking, "unknown must block a required gate, never pass silently"


def test_not_applicable_when_evidence_is_an_explicit_empty_list() -> None:
    """Mirrors evaluate_command rather than reporting a pass.

    A caller submits an empty list for exactly the events that carry no path
    evidence at all (a PreToolUse call for Bash rather than an edit tool).
    PASS there reads as a check that ran and found nothing, when this gate
    never had anything to check. Both are non-blocking, so this is about what
    gets reported, not what gets enforced.
    """
    result = evaluate_path(_gate(), PathEvidence(paths=()))
    assert result.outcome is Outcome.NOT_APPLICABLE
    assert not result.outcome.is_blocking


def test_star_does_not_cross_a_path_segment() -> None:
    gate = _gate(forbidden=("src/*.py",))
    # A single '*' must not match the nested file: only a direct child of src/ counts.
    result = evaluate_path(gate, PathEvidence(paths=("src/gateway/cli.py",)))
    assert result.outcome is Outcome.PASS


def test_double_star_crosses_path_segments() -> None:
    gate = _gate(forbidden=("src/**",))
    result = evaluate_path(gate, PathEvidence(paths=("src/gateway/cli.py",)))
    assert result.outcome is Outcome.FAIL


def test_advisory_gate_does_not_block_required() -> None:
    gate = _gate(enforcement="advisory")
    result = evaluate_path(gate, PathEvidence(paths=("CHANGELOG.md",)))
    assert result.outcome is Outcome.FAIL
    assert result.enforcement == "advisory"


# --- _segment_matches: correctness -----------------------------------------
#
# A prior version of this matcher had two review-caught bugs: a false
# negative ('*a' failed to match 'a', which could let a forbidden path pass
# undetected) and an O(pattern * text) rescan on mismatch that a naive
# backtracking regex would also have had (just with a lower, non-exponential
# ceiling). Both are pinned here so neither can silently come back.


def test_leading_star_matches_with_zero_characters_consumed() -> None:
    assert _segment_matches("*a", "a") is True


def test_trailing_star_matches_with_zero_characters_consumed() -> None:
    assert _segment_matches("a*", "a") is True


def test_star_matches_the_empty_segment() -> None:
    assert _segment_matches("*", "") is True


def test_empty_pattern_matches_only_empty_text() -> None:
    assert _segment_matches("", "") is True
    assert _segment_matches("", "x") is False


def test_adjacent_stars_behave_as_one() -> None:
    assert _segment_matches("a***b", "ab") is True
    assert _segment_matches("a***b", "axyzb") is True
    assert _segment_matches("a***b", "ba") is False


def test_multiple_middle_chunks_match_in_order() -> None:
    assert _segment_matches("a*b*c", "aXbYc") is True
    assert _segment_matches("a*b*c", "aXYc") is False  # no 'b' between the anchors
    assert _segment_matches("a*b*c", "cba") is False  # right characters, wrong order


# --- _segment_matches: the two adversarial patterns from review -------------


def test_original_adversarial_pattern_resolves_quickly() -> None:
    """The initial regex-based fix's ReDoS: many 'a*' repeats, no closing match."""
    pattern = "a*" * 30 + "END"
    start = time.time()
    result = _segment_matches(pattern, "a" * 200)
    assert time.time() - start < 0.1
    assert result is False


def test_long_literal_suffix_after_a_single_star_resolves_quickly() -> None:
    """The rescan bug the two-pointer fix introduced: no repeated backtracking

    is possible now, since each literal chunk is located once, but this is
    exactly the shape (long literal after '*', no match at the end) that
    made the two-pointer version measure seconds against just a few paths.
    """
    pattern = "*" + "a" * 2048 + "b"
    paths = tuple(f"path{i}.txt" for i in range(10))
    start = time.time()
    results = [_segment_matches(pattern, path) for path in paths]
    assert time.time() - start < 0.1
    assert not any(results)


# --- _segments_match: '**' crossing directories -----------------------------


def test_double_star_requires_at_least_one_segment() -> None:
    assert _segments_match(["src", "**"], ["src"]) is False
    assert _segments_match(["src", "**"], ["src", "a"]) is True


def test_double_star_with_segments_on_both_sides() -> None:
    pattern = ["src", "**", "tests", "*.py"]
    assert _segments_match(pattern, ["src", "middle", "tests", "x.py"]) is True
    assert _segments_match(pattern, ["src", "a", "b", "tests", "x.py"]) is True
    assert _segments_match(pattern, ["src", "tests", "x.py"]) is False  # nothing for ** to consume


def test_leading_double_star() -> None:
    assert _segments_match(["**", "foo.py"], ["a", "b", "foo.py"]) is True
    assert _segments_match(["**", "foo.py"], ["foo.py"]) is False  # still needs >=1 segment
