"""Autogenerate against a database that holds tables from another migration chain beside otari's."""

from collections.abc import Generator

import pytest
from alembic import command
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import MetaData, create_engine, text

from gateway.models.base import Base

from .conftest import alembic_config

_FOREIGN_TABLE = "edition_widgets"


@pytest.fixture
def foreign_table(postgres_url: str, clean_database: None) -> Generator[str]:
    """Create a table, with an index, that no revision in otari's chain creates."""
    engine = create_engine(postgres_url)
    with engine.begin() as connection:
        connection.execute(text(f"CREATE TABLE {_FOREIGN_TABLE} (id integer PRIMARY KEY, name text)"))
        connection.execute(text(f"CREATE INDEX ix_{_FOREIGN_TABLE}_name ON {_FOREIGN_TABLE} (name)"))
    try:
        yield _FOREIGN_TABLE
    finally:
        with engine.begin() as connection:
            connection.execute(text(f"DROP TABLE IF EXISTS {_FOREIGN_TABLE}"))
        engine.dispose()


def _proposed_operations(database_url: str) -> str:
    """Return the operations autogenerate proposes for the database, as text, or an empty string for none."""
    try:
        command.check(alembic_config(database_url))
    except AutogenerateDiffsDetected as exc:
        return str(exc)
    return ""


def test_autogenerate_proposes_nothing_for_a_table_outside_the_chain(postgres_url: str, foreign_table: str) -> None:
    assert foreign_table not in _proposed_operations(postgres_url)


def test_autogenerate_still_drops_every_table_the_models_stop_declaring(
    postgres_url: str, clean_database: None, monkeypatch: pytest.MonkeyPatch
) -> None:
    declared = sorted(Base.metadata.tables)
    monkeypatch.setattr(Base, "metadata", MetaData())
    proposed = _proposed_operations(postgres_url)
    assert [name for name in declared if f"('remove_table', Table('{name}'" not in proposed] == []
