// The dashboard's view of the gateway API, generated from its OpenAPI spec.
//
// `./schema.ts` is generated by `pnpm run client:generate` and never edited; it
// carries every request and response shape the gateway serves. This module is
// the only hand-written part, and it does one thing: give those shapes the names
// the dashboard already calls them by. No structure is declared here, so a field
// that changes in the gateway changes here the next time the spec is generated,
// and every consumer sees it.
//
// The handful of shapes the spec does not describe live in `./local.ts`, with
// the reason each one is there.

import type { PolicySpec, UsageFilters } from "./local"
import type { components, operations } from "./schema"

export type { components, operations, paths } from "./schema"

type Schemas = components["schemas"]

/**
 * Make a named set of fields optional, where the generator promised them.
 *
 * The generator marks a property with a schema default as always present, which
 * is true of a response and false of a request body: the point of a default is
 * that a client may omit it. Applied only where the dashboard actually omits
 * one, so it stays a correction rather than a blanket loosening.
 *
 * Exported because the response side has the same problem from the other
 * direction: a gateway older than a field does not send it, whatever the
 * current schema says. `WireBootstrap` in `shared/helpers/bootstrap.ts` is that
 * case, and reuses this rather than restating it.
 */
export type Defaulted<T, K extends keyof T> = Omit<T, K> & Partial<Pick<T, K>>

// ---------------------------------------------------------------------------
// Deployment bootstrap
//
// The first thing the shell reads, and the only response it reads before it
// knows whether it can authenticate at all.
// ---------------------------------------------------------------------------
export type DeploymentBootstrap = Schemas["DeploymentBootstrap"]
export type DeploymentType = DeploymentBootstrap["deployment_type"]
export type SessionType = DeploymentBootstrap["session_type"]

/**
 * `GET /health`, which the hybrid landing page reads for its two status rows.
 *
 * A flat string map rather than a named schema, because the route returns one:
 * `status` always, plus `mode` and `platform_reachable` ("yes" / "no") when the
 * gateway is attached to a control plane. Derived from the operation rather than
 * restated, but an index signature cannot police key names, so nothing here
 * would notice one being renamed: what pins the keys is
 * `test_hybrid_mode_health_reports_reachability`, which asserts the whole dict.
 * Giving the route a response model is what would move that guarantee into the
 * type.
 */
export type GatewayHealth =
  operations["health-health_check"]["responses"][200]["content"]["application/json"]

// ---------------------------------------------------------------------------
// Dashboard sign-in credentials
//
// `PUT /v1/auth/password` always acts on the caller's own identity, so there is
// no id in either shape. The session exchange itself is not here: it predates
// the generated client and stays hand-written in `shared/api/client.ts` with
// the 401 bounce it shares a file with.
// ---------------------------------------------------------------------------
export type SetPasswordRequest = Schemas["SetPasswordRequest"]
export type PasswordResponse = Schemas["PasswordResponse"]

// ---------------------------------------------------------------------------
// The one thing about itself an identity may change that is not a credential:
// the name it goes by. `PATCH /v1/auth/profile` answers with the same
// `CallerIdentity` the membership context carries, so the account page can seat
// the new name where the shell read the old one.
// ---------------------------------------------------------------------------
export type UpdateProfileRequest = Schemas["UpdateProfileRequest"]

// ---------------------------------------------------------------------------
// The public auth flows (otari#650): signup, email verification, and password
// recovery. Every one of them answers a caller who holds neither the master key
// nor a session, so the address or the token in the request is the whole of
// what the gateway has to go on, and each response is deliberately the same
// whether or not there was anything to act on.
//
// `terms_accepted` carries a schema default, which the generator emits as
// required; the signup form omits it when this deployment publishes no terms,
// so `Defaulted` puts that back.
// ---------------------------------------------------------------------------
export type SignupRequest = Defaulted<
  Schemas["SignupRequest"],
  "terms_accepted"
>
export type SignupResponse = Schemas["SignupResponse"]
export type VerifyEmailResponse = Schemas["VerifyEmailResponse"]
export type ResendVerificationResponse = Schemas["ResendVerificationResponse"]
export type RequestPasswordResetResponse =
  Schemas["RequestPasswordResetResponse"]
export type ResetPasswordRequest = Schemas["ResetPasswordRequest"]

// ---------------------------------------------------------------------------
// Passkeys (otari#652)
//
// The two ceremony payloads are deliberately absent. A ceremony's options and
// the browser's answer are W3C shapes the gateway passes through as free-form
// objects, and the only consumer is `navigator.credentials`, which types them
// itself through the DOM lib. Naming a second, looser copy of them here would
// make it possible to pass the wrong one.
// ---------------------------------------------------------------------------
export type Passkey = Schemas["WebAuthnCredentialPublic"]
export type PasskeysResponse = Schemas["WebAuthnCredentialsPublic"]
export type RenamePasskeyRequest = Schemas["WebAuthnCredentialUpdate"]

// ---------------------------------------------------------------------------
// Usage and analytics
// ---------------------------------------------------------------------------
export type UsageEntry = Schemas["UsageEntry"]
export type UsageCount = Schemas["UsageCount"]
export type UsageTotals = Schemas["UsageTotals"]
export type UsageSummary = Schemas["UsageSummary"]
export type UsageGroupRow = Schemas["UsageGroupRow"]
export type UsageSeriesPoint = Schemas["UsageSeriesPoint"]
export type UsageGroupedSeries = Schemas["UsageGroupedSeries"]
export type UsageGroupedSeriesPoint = Schemas["UsageGroupedSeriesPoint"]
export type UsageDeleteResult = Schemas["UsageDeleteResult"]
export type UsageMutationSelection = Defaulted<
  Schemas["UsageDeleteRequest"],
  "by_filter"
>
export type UsageSetPriceRequest = Defaulted<
  Schemas["UsageSetPriceRequest"],
  "by_filter"
>
export type UsageSetPriceResult = Schemas["UsageSetPriceResult"]
export type InFlightRequest = Schemas["InFlightEntry"]
export type InFlightResponse = Schemas["InFlightResponse"]

// The charge lines on a row's `pricing_breakdown`, which carry either a
// per-million or a per-call rate.
export type TokenChargeLine = Schemas["TokenChargeLine"]
export type UnitChargeLine = Schemas["UnitChargeLine"]
/** One line of a row's `pricing_breakdown`, of whichever of the three shapes. */
export type ChargeLine = NonNullable<UsageEntry["pricing_breakdown"]>[number]

// Which rate a line carries is what says how to read it, and the third arm of
// the union is a line whose shape the gateway no longer writes (see the spec's
// TokenChargeLine / UnitChargeLine). These guards live here rather than at the
// one call site because the union is the generated client's, and a renderer that
// assumed two arms would print an undefined rate for the third.
//
// They check the fields they promise rather than just the discriminator's
// presence. The permissive arm is any object at all, so a legacy line carrying
// `unit_rate: "flat"` would otherwise be narrowed to a typed shape and rendered
// with a non-numeric rate and no units, which is worse than falling through to
// the untyped branch that shows the recorded cost and nothing it cannot vouch for.
function hasChargeFields(
  line: ChargeLine,
): line is ChargeLine & { meter: string; units: number; cost: number } {
  if (typeof line !== "object" || line === null) return false
  const candidate = line as Record<string, unknown>
  return (
    typeof candidate.meter === "string" &&
    typeof candidate.units === "number" &&
    typeof candidate.cost === "number"
  )
}
export function isUnitChargeLine(line: ChargeLine): line is UnitChargeLine {
  return (
    hasChargeFields(line) &&
    typeof (line as Record<string, unknown>).unit_rate === "number"
  )
}
export function isTokenChargeLine(line: ChargeLine): line is TokenChargeLine {
  return (
    hasChargeFields(line) &&
    typeof (line as Record<string, unknown>).rate_per_million === "number"
  )
}
export type BillingMeters = Schemas["BillingMeters"]
export type ToolMeter = Schemas["ToolMeter"]

// Query-parameter enums. The spec carries these inline on the operation rather
// than as named schemas, so they are pinned to the operation instead of being
// restated as literal unions that could drift.
type SummaryQuery = NonNullable<
  operations["usage-usage_summary"]["parameters"]["query"]
>
export type UsageBucket = NonNullable<SummaryQuery["bucket"]>
export type SummaryDimension = NonNullable<SummaryQuery["dimensions"]>[number]
type SeriesQuery = NonNullable<
  operations["usage-usage_series"]["parameters"]["query"]
>
export type UsageGroupBy = NonNullable<SeriesQuery["group_by"]>

// `UsageFilters` (`./local`) stays hand-written, because it is a filter set the
// hooks assemble across five usage endpoints and several of its values go on the
// wire as repeated params, which no request body in the spec describes. What it
// must not be is unbound: a key that is not a real query parameter would be
// serialized and ignored, and nothing would say so. So its keys are pinned to
// the operation that carries all of them, and a name the spec drops (or a typo)
// fails to compile here rather than going quiet on the wire.
type RequestsQuery = NonNullable<
  operations["usage-list_usage"]["parameters"]["query"]
>
/** Fails to compile unless `T` is `true`, so a `false` below is a build error. */
type Assert<T extends true> = T
export type UsageFilterKeysArePinned = Assert<
  keyof UsageFilters extends keyof RequestsQuery ? true : false
>

// ---------------------------------------------------------------------------
// Users, keys and budgets
// ---------------------------------------------------------------------------
export type User = Schemas["UserResponse"]
export type CreateUserRequest = Defaulted<
  Schemas["CreateUserRequest"],
  "blocked"
>
export type UpdateUserRequest = Schemas["UpdateUserRequest"]
export type ApiKey = Schemas["KeyInfo"]
export type CreateKeyRequest = Schemas["CreateKeyRequest"]
export type CreateKeyResponse = Schemas["CreateKeyResponse"]
export type UpdateKeyRequest = Schemas["UpdateKeyRequest"]
// The member surface's bodies (otari-ai#1941): the operator shapes minus the
// owner and the budget exemption, which that surface derives or refuses.
export type CreateOwnKeyRequest = Schemas["CreateOwnKeyRequest"]
export type UpdateOwnKeyRequest = Schemas["UpdateOwnKeyRequest"]
export type Budget = Schemas["BudgetResponse"]
export type CreateBudgetRequest = Schemas["CreateBudgetRequest"]
export type UpdateBudgetRequest = Schemas["UpdateBudgetRequest"]
export type BudgetResetLog = Schemas["BudgetResetLogResponse"]

// A ceiling names a `Budget` and holds the counters for spending it. It is not a
// variant of a budget: a budget is the only shape that maps a cap to an amount,
// and the two differ in what they enforce against. A budget reached through
// `User.budget_id` is checked against that person's own spend, so N people on one
// budget each get the full amount. A budget reached through a ceiling is checked
// against the ceiling's counters, so everyone the scope names shares one
// allowance. `max_budget` and the cadence travel on a ceiling's wire shape but
// are read off the budget, never stored on it.
//
// `provider_key_id` is the odd name here and it is the wire's, not ours: the
// column holds a provider *instance* name (`openai`, or a configured instance),
// which is what `scoped_budget_service` matches a request's resolved provider
// against. Anything picking a value for it wants `ProviderInfo["instance"]`.
export type ScopedBudget = Schemas["ScopedBudgetResponse"]
export type CreateScopedBudgetRequest = Schemas["CreateScopedBudgetRequest"]
export type UpdateScopedBudgetRequest = Schemas["UpdateScopedBudgetRequest"]
export type BudgetScopeType = CreateScopedBudgetRequest["scope_type"]
// The cadence moved onto the budget with the limit, so it is derived from the
// budget request now rather than from the ceiling's.
export type BudgetResetAlignment = NonNullable<
  CreateBudgetRequest["reset_alignment"]
>

// ---------------------------------------------------------------------------
// Models, pricing and providers
// ---------------------------------------------------------------------------
export type ModelObject = Schemas["ModelObject"]
export type ModelListResponse = Schemas["ModelListResponse"]
export type ModelPricingInfo = Schemas["ModelPricingInfo"]
export type ModelMetadata = Schemas["ModelMetadata"]
export type ModelMetadataResponse = Schemas["ModelMetadataResponse"]
export type DiscoverableModel = Schemas["DiscoverableModel"]
export type DiscoverableProvider = Schemas["DiscoverableProvider"]
export type DiscoverableModelsResponse = Schemas["DiscoverableModelsResponse"]
export type PricingResponse = Schemas["PricingResponse"]
export type PricingTier = Schemas["PricingTier"]

// The catalog folded by model (`/v1/catalog`): one summary per model in the
// list, and one detail carrying every offering of it the caller may use.
export type CatalogResponse = Schemas["CatalogResponse"]
export type CatalogModelSummary = Schemas["CatalogModelSummary"]
export type CatalogModelDetail = Schemas["CatalogModelDetail"]
export type CatalogOffering = Schemas["CatalogOffering"]
export type CatalogCapabilities = Schemas["CatalogCapabilities"]
export type CatalogElsewhere = Schemas["CatalogElsewhere"]
export type CatalogOfferingUsage = Schemas["OfferingUsage"]
/** A tier as stored, which may be a shape this client cannot read (see the spec). */
export type StoredPricingTier = NonNullable<
  ModelPricingInfo["pricing_tiers"]
>[number]
// A tier whose threshold is unreadable cannot take part in choosing a rate, and
// it already could not: comparing against an absent `min_input_tokens` excluded
// it anyway. Narrowing says so rather than leaving it to a false comparison.
export function isPricingTier(tier: StoredPricingTier): tier is PricingTier {
  return (
    typeof tier === "object" &&
    tier !== null &&
    typeof (tier as PricingTier).min_input_tokens === "number"
  )
}
// `unit` carries a schema default, so the generator emits it as required; the
// callers that price a model omit it and the gateway reads tokens.
export type SetPricingRequest = Defaulted<Schemas["SetPricingRequest"], "unit">
// Per-organization rate overrides, which sit above the deployment price list
// above. Same DTO names as otari.ai's own endpoint, so the two clients stay
// recognizable side by side.
export type OrganizationPricingOverride =
  Schemas["OrganizationModelPricingPublic"]
export type OrganizationPricingOverrides =
  Schemas["OrganizationModelPricingsPublic"]
export type CreateOrganizationPricingOverride = Defaulted<
  Schemas["OrganizationModelPricingCreate"],
  "unit"
>
export type UpdateOrganizationPricingOverride = Defaulted<
  Schemas["OrganizationModelPricingUpdate"],
  "unit"
>
// The organization's own budgets and the ceilings enforcing them, which are the
// tenant-scoped counterparts to `Budget` and `ScopedBudget` above. Separate
// types rather than the same ones: these carry an owner and, on a ceiling,
// whether its figure is this organization's to change.
export type OrganizationBudget = Schemas["OrganizationBudgetPublic"]
export type CreateOrganizationBudget = Schemas["OrganizationBudgetCreate"]
export type UpdateOrganizationBudget = Schemas["OrganizationBudgetUpdate"]
export type OrganizationSpendCeiling = Schemas["OrganizationScopedBudgetPublic"]
export type CreateOrganizationSpendCeiling =
  Schemas["OrganizationScopedBudgetCreate"]
export type UpdateOrganizationSpendCeiling =
  Schemas["OrganizationScopedBudgetUpdate"]
export type PricingRefreshChange = Schemas["PricingRefreshChangeResponse"]
export type PricingRefreshPreview = Schemas["PricingRefreshPreviewResponse"]
export type AcceptedPricingSnapshot = Schemas["AcceptedSnapshotResponse"]
export type PricingDriftRow = Schemas["PricingDriftRow"]
export type ProviderInfo = Schemas["ProviderInfoSchema"]
export type ProviderCapabilities = Schemas["ProviderCapabilitiesSchema"]
export type ProvidersResponse = Schemas["ProvidersResponse"]
export type ProviderHealth = Schemas["ProviderHealthSchema"]
export type ProviderHealthResponse = Schemas["ProviderHealthResponse"]
export type StoredProvider = Schemas["StoredProviderResponse"]
export type CreateStoredProviderRequest = Schemas["CreateStoredProviderRequest"]
export type UpdateStoredProviderRequest = Schemas["UpdateStoredProviderRequest"]
export type TestProviderResult = Schemas["TestProviderResponse"]
export type ReencryptProviderCredentialsResult =
  Schemas["ReencryptProviderCredentialsResponse"]
export type KnownProvider = Schemas["KnownProviderSchema"]
export type KnownProviderSummary = Schemas["KnownProviderSummarySchema"]

// The organization's own upstream credentials, which are a different table from
// the four above: a `StoredProvider` is keyed on an instance name and belongs to
// the process, an `OrgProviderKey` belongs to a tenant and every workspace in it
// inherits it. Only a hosted deployment shows both concepts, and it shows only
// this one (`organization_providers` in `GET /v1/bootstrap`'s surfaces).
export type OrgProviderKey = Schemas["OrgProviderKeyPublic"]
// No alias for the list wrapper: this surface is read through `fetchAllPaged`,
// which types the envelope itself, so a name for it would have no consumer.
export type CreateOrgProviderKeyRequest = Schemas["OrgProviderKeyCreateRequest"]
export type UpdateOrgProviderKeyRequest = Schemas["OrgProviderKeyUpdateRequest"]

// An organization's email-domain claims. A claim is inert until its DNS TXT
// record is found, so `verified_at` is the field the UI branches on and
// `verification_record` is the whole string an admin publishes.
export type OrganizationDomain = Schemas["OrganizationDomainPublic"]
export type CreateOrganizationDomainRequest =
  Schemas["OrganizationDomainCreateRequest"]
export type UpdateOrganizationDomainRequest =
  Schemas["OrganizationDomainUpdateRequest"]

// ---------------------------------------------------------------------------
// Routing
// ---------------------------------------------------------------------------
// `spec` is the one field taken from ./local rather than the generator: the wire
// contract declares it a free-form object, so the generated type is
// `Record<string, unknown>` and the Routing page reads its internals. Everything
// else on these two comes from the spec.
export type RoutingPolicyResponse = Omit<Schemas["PolicyResponse"], "spec"> & {
  spec: PolicySpec
}
export type SetRoutingPolicyRequest = Omit<Schemas["PolicyRequest"], "spec"> & {
  spec: PolicySpec
}
export type AliasResponse = Schemas["AliasResponse"]
export type CreateAliasRequest = Schemas["AliasRequest"]
export type ExplainPolicyRequest = Schemas["ExplainRequest"]
export type ExplainPolicyResponse = Schemas["ExplainResponse"]
export type RouterStatus = Schemas["RouterStatus"]
export type RouterPool = Schemas["PoolStatus"]
export type LearnedPolicy = Schemas["LearnedPolicy"]
export type RecordedPool = Schemas["RecordedPool"]
export type ScoredExample = Schemas["ScoredExample"]
export type RankCandidatesRequest = Schemas["RankRequest"]
export type RankCandidatesResponse = Schemas["RankResponse"]

// ---------------------------------------------------------------------------
// Settings, tools and guardrails
// ---------------------------------------------------------------------------
export type GatewaySettings = Schemas["GatewaySettings"]
export type UpdateSettingsRequest = Schemas["UpdateSettingsRequest"]
export type ConfigField = Schemas["ConfigField"]
export type ConfigFieldType = ConfigField["type"]
export type RotateMasterKeyResponse = Schemas["RotateMasterKeyResponse"]
export type MailSettings = Schemas["MailSettings"]
export type SendTestMailRequest = Schemas["SendTestMailRequest"]
export type SendTestMailResponse = Schemas["SendTestMailResponse"]
export type MaintenanceMode = Schemas["MaintenanceMode"]
export type UpdateMaintenanceModeRequest =
  Schemas["UpdateMaintenanceModeRequest"]
export type ManagedTool = Schemas["ManagedTool"]
export type ToolsResponse = Schemas["ToolsResponse"]
export type ToolSettingField = Schemas["ToolSettingField"]
export type ToolSettingType = ToolSettingField["type"]
export type ToolSettingsResponse = Schemas["ToolSettingsResponse"]
export type UpdateToolSettingsRequest = Schemas["UpdateToolSettingsRequest"]
export type TestServiceResponse = Schemas["TestServiceResponse"]

// The guardrail catalog behind the mandate form: which profiles the operator's
// guardrails service has built, and the `validate_kwargs` each one accepts. See
// `src/gateway/services/guardrail_catalog.py`.
export type GuardrailCatalog = Schemas["GuardrailCatalog"]
export type GuardrailProfileSpec = Schemas["GuardrailProfileSpec"]
export type GuardrailParameterSpec = Schemas["GuardrailParameterSpec"]
export type GuardrailParameterType = GuardrailParameterSpec["type"]

// ---------------------------------------------------------------------------
// Search tools
// ---------------------------------------------------------------------------
export type SearchProviderInfo = Schemas["SearchProviderSchema"]
export type StoredSearchTool = Schemas["StoredSearchToolSchema"]
export type ConfigSearchTool = Schemas["ConfigSearchToolSchema"]
export type SearchToolsResponse = Schemas["SearchToolsResponse"]
export type CreateSearchToolRequest = Schemas["CreateSearchToolRequest"]
export type UpdateSearchToolRequest = Schemas["UpdateSearchToolRequest"]
export type StreamMissingUsagePolicy = NonNullable<
  UpdateSettingsRequest["stream_missing_usage_policy"]
>
export type VisionStrategy = NonNullable<
  UpdateSettingsRequest["vision_strategy"]
>

// ---------------------------------------------------------------------------
// Tenancy: organizations, workspaces, and the memberships joining them
//
// Rehomed from the platform with their shapes intact, which is the point: the
// pages built on them here are the ones otari.ai's control plane brings across
// at M5, so a renamed field would have to be reconciled twice.
// ---------------------------------------------------------------------------
// One organization is provisioned at first boot and that is what most
// deployments keep, but a second is reachable (an invitation into one elsewhere
// on the deployment), so create, list-mine and switch are all mounted. Delete
// is not, and has no request shape to alias.
export type Organization = Schemas["OrganizationPublic"]
export type CreateOrganizationRequest = Schemas["OrganizationCreateRequest"]
/** One organization the caller belongs to, as the organization switcher renders it. */
export type CallerOrganizationMembership =
  Schemas["CallerOrganizationMembershipPublic"]
export type SwitchOrganizationRequest =
  Schemas["SwitchActiveOrganizationRequest"]
/** An organization plus the caller's standing in it: what every tenancy page reads first. */
export type OrganizationContext = Schemas["OrganizationMembershipContextPublic"]
/** Who is signed in, as against what they may do: the person the chrome draws. */
export type CallerIdentity = Schemas["CallerIdentityPublic"]
// The caller's own workspace memberships, carried on the context so the shell
// can seed its switcher from the call it already makes. Not a directory of the
// organization's workspaces: listing those is a separate authorized read.
export type CallerWorkspaceMembership =
  Schemas["CallerWorkspaceMembershipPublic"]
export type UpdateOrganizationRequest =
  Schemas["ActiveOrganizationUpdateRequest"]
export type OrganizationMember = Schemas["ActiveOrganizationMemberPublic"]
export type UpdateOrganizationMemberRequest =
  Schemas["ActiveOrganizationMemberUpdateRequest"]
export type CreateOrganizationMemberRequest = Defaulted<
  Schemas["ActiveOrganizationMemberCreateRequest"],
  "role"
>
export type CreateOrganizationMemberResult =
  Schemas["ActiveOrganizationMemberCreateResultPublic"]
// Not `Defaulted`: the form states the role it grants rather than leaving it to
// the server, and `Defaulted` is for the fields the dashboard actually omits.
export type WorkspaceAssignment = Schemas["WorkspaceAssignmentRequest"]

// The role and status vocabularies, taken from the requests that *set* one
// rather than restated as literal unions. The gateway publishes them as enums
// now, so a value this edition refuses cannot reach a picker: the two that
// matter are that "invited" is a status a membership may hold and not one it may
// be given, and that a workspace role travels as a query parameter, so its
// vocabulary is pinned to the operation rather than to a body schema.
export type MembershipRole =
  Schemas["ActiveOrganizationMemberCreateRequest"]["role"]
export type SettableMemberStatus = NonNullable<
  Schemas["ActiveOrganizationMemberUpdateRequest"]["status"]
>
export type WorkspaceMemberRole = NonNullable<
  NonNullable<
    operations["workspaces-add_workspace_member"]["parameters"]["query"]
  >["role"]
>
// ---------------------------------------------------------------------------
// Deployment administration
//
// The one management prefix scoped to the deployment rather than to an
// organization. Every shape above reads through a membership and so cannot see
// an account whose memberships are all suspended, which is what this one is for.
// ---------------------------------------------------------------------------
/** Whether the caller may use the surface at all: what the sidebar gates on. */
export type DeploymentAdminAccess = Schemas["DeploymentAdminAccessPublic"]
/** One account on the deployment, with every organization it belongs to. */
export type DeploymentUser = Schemas["DeploymentUserPublic"]
/** One organization an account belongs to, at whatever standing. */
export type DeploymentUserOrganization =
  Schemas["DeploymentUserOrganizationPublic"]
export type UpdateDeploymentUserRequest = Schemas["DeploymentUserUpdateRequest"]
/** A generated password, returned once: only its hash is stored. */
export type DeploymentUserPassword = Schemas["DeploymentUserPasswordPublic"]
/** Fold one request-plane user into another: keys, usage and per-user state. */
export type MergeUserRequest = Schemas["MergeUserRequest"]
export type MergeUserResult = Schemas["MergeUserResponse"]

export type Workspace = Schemas["WorkspacePublic"]
export type CreateWorkspaceRequest = Schemas["WorkspaceCreate"]
export type UpdateWorkspaceRequest = Schemas["WorkspaceUpdate"]
export type WorkspaceMember = Schemas["WorkspaceMemberPublic"]

// Invitations: the emailed half of adding a member. `InviteOrganizationMemberRequest`
// is `CreateOrganizationMemberRequest`'s twin (same fields, different result:
// `invited` and an accept link rather than `active` immediately), so it is
// `Defaulted` on the same field for the same reason.
export type InviteOrganizationMemberRequest = Defaulted<
  Schemas["InviteOrganizationMemberRequest"],
  "role"
>
export type InviteOrganizationMemberResult =
  Schemas["InviteOrganizationMemberResultPublic"]
export type InvitationPreview = Schemas["InvitationPreviewPublic"]
export type AcceptInvitationResult = Schemas["AcceptInvitationResultPublic"]

// The invitee's side of the same flow: what is waiting on the signed-in
// identity, rather than what this organization has sent out. Addressed by
// `organization_member_id`, not by token, because the caller is already the
// addressee (otari-ai#1999).
export type PendingOrganizationInvitation =
  Schemas["PendingOrganizationInvitationPublic"]

// A workspace-level template for a per-member `scoped_budgets` ceiling; see
// `src/gateway/services/tenancy/workspace_budget_default_service.py`. The DTO
// name is `WorkspaceMemberBudgetPolicy*` on the wire (kept recognizable
// against otari-ai's own hosted equivalent); the dashboard's own name for the
// concept is "budget default".
export type WorkspaceBudgetDefault =
  Schemas["WorkspaceMemberBudgetPolicyPublic"]
export type CreateWorkspaceBudgetDefaultRequest =
  Schemas["WorkspaceMemberBudgetPolicyCreate"]
export type UpdateWorkspaceBudgetDefaultRequest =
  Schemas["WorkspaceMemberBudgetPolicyUpdate"]

// One workspace's departure from the organization key above: pinned as this
// workspace's default, opted out of, or neither. `is_default`/`disabled` are the
// stored flags and `is_effective_*` the resolution across the provider's keys,
// so a row can be unpinned and still effective (it is the organization default,
// or the only key that provider has).
export type WorkspaceProviderKeyOverride =
  Schemas["WorkspaceProviderKeyOverridePublic"]
// Tri-state on the way in: an omitted flag is left unchanged, so the dashboard
// sends one at a time and lets the gateway resolve the other.
export type SetWorkspaceProviderKeyOverrideRequest =
  Schemas["WorkspaceProviderKeyOverrideRequest"]

// The first-request setup guide's state, and the API key it issues. The wire
// names carry the platform's "activation" vocabulary (see
// `src/gateway/services/tenancy/workspace_activation_service.py`); the
// dashboard calls the thing an operator sees the setup guide.
export type WorkspaceActivation = Schemas["WorkspaceActivationPublic"]
export type ActivationAttempt = Schemas["ActivationAttemptPublic"]
export type ActivationApiKey = Schemas["ActivationApiKeyPublic"]
/** The failure classes the guide's copy is written for. */
export type ActivationErrorCategory = NonNullable<
  ActivationAttempt["error_category"]
>

// The per-workspace code-execution policy over the deployment-wide sandbox; see
// `src/gateway/services/tenancy/workspace_code_execution_policy_service.py`.
export type WorkspaceCodeExecutionPolicy =
  Schemas["WorkspaceCodeExecutionPolicyPublic"]
export type UpdateWorkspaceCodeExecutionPolicyRequest =
  Schemas["WorkspaceCodeExecutionPolicyUpdate"]

// The per-workspace web-search configuration over the deployment-wide backend;
// see `src/gateway/services/tenancy/workspace_web_search_service.py`.
export type WorkspaceWebSearchConfig = Schemas["WorkspaceWebSearchConfigPublic"]
export type UpdateWorkspaceWebSearchConfigRequest =
  Schemas["WorkspaceWebSearchConfigUpdate"]
// The organization-level guardrail plane above the deployment-wide guardrail
// settings; see `src/gateway/services/tenancy/organization_guardrail_service.py`.
export type OrganizationGuardrail = Schemas["OrganizationGuardrailPublic"]
// `enabled`, `on_unavailable`, `mode` and `applies_to_all_workspaces` all carry
// schema defaults, which the generator emits as required; the add form omits the
// two the operator has no control for, so `Defaulted` puts them back.
export type CreateOrganizationGuardrailRequest = Defaulted<
  Schemas["OrganizationGuardrailCreate"],
  "enabled" | "on_unavailable" | "mode" | "applies_to_all_workspaces"
>
export type UpdateOrganizationGuardrailRequest =
  Schemas["OrganizationGuardrailUpdate"]

// The MCP servers a workspace has registered, which a request names by id in
// `mcp_server_ids`; see
// `src/gateway/services/tenancy/workspace_mcp_server_service.py`. The stored
// bearer token is write-only, so the public shape reports only `has_token`.
export type WorkspaceMcpServer = Schemas["WorkspaceMcpServerPublic"]
export type WorkspaceMcpServers = Schemas["WorkspaceMcpServersPublic"]
export type CreateWorkspaceMcpServerRequest =
  Schemas["WorkspaceMcpServerCreate"]
export type UpdateWorkspaceMcpServerRequest =
  Schemas["WorkspaceMcpServerUpdate"]

// ---------------------------------------------------------------------------
// Playground
//
// The dashboard's own chat page; see `src/gateway/api/routes/playground.py`.
// Its completion endpoint takes the ordinary chat request body, so the shapes
// named here are the page's memory (consent, saved transcripts, rated
// comparisons, pinned models) and the tools menu's availability read.
// ---------------------------------------------------------------------------
export type PlaygroundConsent = Schemas["PlaygroundConsentPublic"]
export type PlaygroundConsentUpdate = Schemas["PlaygroundConsentUpdate"]

// Three states from two fields: a tool the deployment never configured, one a
// workspace turned off (with the reason), and one that can be attached.
export type PlaygroundToolStatus = Schemas["PlaygroundToolStatus"]
export type PlaygroundTools = Schemas["PlaygroundToolsResponse"]
export type PlaygroundMcpServer = Schemas["PlaygroundMcpServer"]

// A saved transcript. The list carries a turn count and not the turns, so
// loading one back into the page is a second request.
export type PlaygroundConversation = Schemas["PlaygroundConversationSummary"]
export type PlaygroundConversations = Schemas["PlaygroundConversationsPublic"]
export type SavePlaygroundConversationRequest =
  Schemas["PlaygroundConversationCreate"]
export type PlaygroundMessage = Schemas["PlaygroundMessagePublic"]
export type PlaygroundMessages = Schemas["PlaygroundMessagesPublic"]

// A rated A/B exchange. The summary deliberately carries no answer bodies;
// there is no endpoint that reads one back, because a comparison is a recorded
// judgment rather than a transcript to resume.
export type PlaygroundComparison = Schemas["PlaygroundComparisonSummary"]
export type PlaygroundComparisons = Schemas["PlaygroundComparisonsPublic"]
export type SavePlaygroundComparisonRequest =
  Schemas["PlaygroundComparisonCreate"]
export type PlaygroundComparisonPreference =
  SavePlaygroundComparisonRequest["preference"]

export type PlaygroundFavoriteModels = Schemas["PlaygroundFavoriteModelsPublic"]
export type PlaygroundFavoriteModelsUpdate =
  Schemas["PlaygroundFavoriteModelsUpdate"]

// The OAuth sign-in pair; see `src/gateway/api/routes/auth_oauth.py`. Named
// here rather than hand-written at the call site so the authorization response
// and the callback body cannot drift from the spec without a type error.
export type OAuthAuthorizeResponse = Schemas["AuthorizeResponse"]
export type OAuthCallbackRequest = Schemas["OAuthCallbackRequest"]

export type * from "./local"
