/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AccountRouteImport } from './routes/account'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AliasesRouteImport } from './routes/aliases'
import { Route as BudgetsRouteImport } from './routes/budgets'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as InvitationsRouteImport } from './routes/invitations'
import { Route as KeysRouteImport } from './routes/keys'
import { Route as MembersRouteImport } from './routes/members'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as OrganizationRouteImport } from './routes/organization'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as RoutingRouteImport } from './routes/routing'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as AdminAccountsRouteImport } from './routes/admin.accounts'
import { Route as ModelsIndexRouteImport } from './routes/models.index'
import { Route as ModelsSplatRouteImport } from './routes/models.$'
import { Route as OrganizationIndexRouteImport } from './routes/organization.index'
import { Route as OrganizationDomainsRouteImport } from './routes/organization.domains'
import { Route as OrganizationMembersRouteImport } from './routes/organization.members'
import { Route as OrganizationPricingRouteImport } from './routes/organization.pricing'
import { Route as OrganizationProviderKeysRouteImport } from './routes/organization.provider-keys'
import { Route as OrganizationUsageRouteImport } from './routes/organization.usage'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as ToolsCodeExecutionRouteImport } from './routes/tools.code-execution'
import { Route as ToolsMcpServersRouteImport } from './routes/tools.mcp-servers'
import { Route as ToolsWebSearchRouteImport } from './routes/tools.web-search'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AliasesRoute = AliasesRouteImport.update({
  id: '/aliases',
  path: '/aliases',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsRoute = BudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsRoute = InvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const KeysRoute = KeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationRoute = OrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutingRoute = RoutingRouteImport.update({
  id: '/routing',
  path: '/routing',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccountsRoute = AdminAccountsRouteImport.update({
  id: '/admin/accounts',
  path: '/admin/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsIndexRoute = ModelsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModelsRoute,
} as any)
const ModelsSplatRoute = ModelsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ModelsRoute,
} as any)
const OrganizationIndexRoute = OrganizationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizationRoute,
} as any)
const OrganizationDomainsRoute = OrganizationDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => OrganizationRoute,
} as any)
const OrganizationMembersRoute = OrganizationMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => OrganizationRoute,
} as any)
const OrganizationPricingRoute = OrganizationPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => OrganizationRoute,
} as any)
const OrganizationProviderKeysRoute =
  OrganizationProviderKeysRouteImport.update({
    id: '/provider-keys',
    path: '/provider-keys',
    getParentRoute: () => OrganizationRoute,
  } as any)
const OrganizationUsageRoute = OrganizationUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => OrganizationRoute,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsCodeExecutionRoute = ToolsCodeExecutionRouteImport.update({
  id: '/code-execution',
  path: '/code-execution',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsMcpServersRoute = ToolsMcpServersRouteImport.update({
  id: '/mcp-servers',
  path: '/mcp-servers',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsWebSearchRoute = ToolsWebSearchRouteImport.update({
  id: '/web-search',
  path: '/web-search',
  getParentRoute: () => ToolsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/account': typeof AccountRoute
  '/activity': typeof ActivityRoute
  '/aliases': typeof AliasesRoute
  '/budgets': typeof BudgetsRoute
  '/docs': typeof DocsRoute
  '/invitations': typeof InvitationsRoute
  '/keys': typeof KeysRoute
  '/members': typeof MembersRoute
  '/models': typeof ModelsRouteWithChildren
  '/organization': typeof OrganizationRouteWithChildren
  '/playground': typeof PlaygroundRoute
  '/providers': typeof ProvidersRoute
  '/routing': typeof RoutingRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/usage': typeof UsageRoute
  '/workspaces': typeof WorkspacesRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/models/$': typeof ModelsSplatRoute
  '/organization/domains': typeof OrganizationDomainsRoute
  '/organization/members': typeof OrganizationMembersRoute
  '/organization/pricing': typeof OrganizationPricingRoute
  '/organization/provider-keys': typeof OrganizationProviderKeysRoute
  '/organization/usage': typeof OrganizationUsageRoute
  '/tools/code-execution': typeof ToolsCodeExecutionRoute
  '/tools/mcp-servers': typeof ToolsMcpServersRoute
  '/tools/web-search': typeof ToolsWebSearchRoute
  '/models/': typeof ModelsIndexRoute
  '/organization/': typeof OrganizationIndexRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/account': typeof AccountRoute
  '/activity': typeof ActivityRoute
  '/aliases': typeof AliasesRoute
  '/budgets': typeof BudgetsRoute
  '/docs': typeof DocsRoute
  '/invitations': typeof InvitationsRoute
  '/keys': typeof KeysRoute
  '/members': typeof MembersRoute
  '/playground': typeof PlaygroundRoute
  '/providers': typeof ProvidersRoute
  '/routing': typeof RoutingRoute
  '/settings': typeof SettingsRoute
  '/usage': typeof UsageRoute
  '/workspaces': typeof WorkspacesRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/models/$': typeof ModelsSplatRoute
  '/organization/domains': typeof OrganizationDomainsRoute
  '/organization/members': typeof OrganizationMembersRoute
  '/organization/pricing': typeof OrganizationPricingRoute
  '/organization/provider-keys': typeof OrganizationProviderKeysRoute
  '/organization/usage': typeof OrganizationUsageRoute
  '/tools/code-execution': typeof ToolsCodeExecutionRoute
  '/tools/mcp-servers': typeof ToolsMcpServersRoute
  '/tools/web-search': typeof ToolsWebSearchRoute
  '/models': typeof ModelsIndexRoute
  '/organization': typeof OrganizationIndexRoute
  '/tools': typeof ToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/account': typeof AccountRoute
  '/activity': typeof ActivityRoute
  '/aliases': typeof AliasesRoute
  '/budgets': typeof BudgetsRoute
  '/docs': typeof DocsRoute
  '/invitations': typeof InvitationsRoute
  '/keys': typeof KeysRoute
  '/members': typeof MembersRoute
  '/models': typeof ModelsRouteWithChildren
  '/organization': typeof OrganizationRouteWithChildren
  '/playground': typeof PlaygroundRoute
  '/providers': typeof ProvidersRoute
  '/routing': typeof RoutingRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/usage': typeof UsageRoute
  '/workspaces': typeof WorkspacesRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/models/$': typeof ModelsSplatRoute
  '/organization/domains': typeof OrganizationDomainsRoute
  '/organization/members': typeof OrganizationMembersRoute
  '/organization/pricing': typeof OrganizationPricingRoute
  '/organization/provider-keys': typeof OrganizationProviderKeysRoute
  '/organization/usage': typeof OrganizationUsageRoute
  '/tools/code-execution': typeof ToolsCodeExecutionRoute
  '/tools/mcp-servers': typeof ToolsMcpServersRoute
  '/tools/web-search': typeof ToolsWebSearchRoute
  '/models/': typeof ModelsIndexRoute
  '/organization/': typeof OrganizationIndexRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/account'
    | '/activity'
    | '/aliases'
    | '/budgets'
    | '/docs'
    | '/invitations'
    | '/keys'
    | '/members'
    | '/models'
    | '/organization'
    | '/playground'
    | '/providers'
    | '/routing'
    | '/settings'
    | '/tools'
    | '/usage'
    | '/workspaces'
    | '/admin/accounts'
    | '/models/$'
    | '/organization/domains'
    | '/organization/members'
    | '/organization/pricing'
    | '/organization/provider-keys'
    | '/organization/usage'
    | '/tools/code-execution'
    | '/tools/mcp-servers'
    | '/tools/web-search'
    | '/models/'
    | '/organization/'
    | '/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/account'
    | '/activity'
    | '/aliases'
    | '/budgets'
    | '/docs'
    | '/invitations'
    | '/keys'
    | '/members'
    | '/playground'
    | '/providers'
    | '/routing'
    | '/settings'
    | '/usage'
    | '/workspaces'
    | '/admin/accounts'
    | '/models/$'
    | '/organization/domains'
    | '/organization/members'
    | '/organization/pricing'
    | '/organization/provider-keys'
    | '/organization/usage'
    | '/tools/code-execution'
    | '/tools/mcp-servers'
    | '/tools/web-search'
    | '/models'
    | '/organization'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/account'
    | '/activity'
    | '/aliases'
    | '/budgets'
    | '/docs'
    | '/invitations'
    | '/keys'
    | '/members'
    | '/models'
    | '/organization'
    | '/playground'
    | '/providers'
    | '/routing'
    | '/settings'
    | '/tools'
    | '/usage'
    | '/workspaces'
    | '/admin/accounts'
    | '/models/$'
    | '/organization/domains'
    | '/organization/members'
    | '/organization/pricing'
    | '/organization/provider-keys'
    | '/organization/usage'
    | '/tools/code-execution'
    | '/tools/mcp-servers'
    | '/tools/web-search'
    | '/models/'
    | '/organization/'
    | '/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AccountRoute: typeof AccountRoute
  ActivityRoute: typeof ActivityRoute
  AliasesRoute: typeof AliasesRoute
  BudgetsRoute: typeof BudgetsRoute
  DocsRoute: typeof DocsRoute
  InvitationsRoute: typeof InvitationsRoute
  KeysRoute: typeof KeysRoute
  MembersRoute: typeof MembersRoute
  ModelsRoute: typeof ModelsRouteWithChildren
  OrganizationRoute: typeof OrganizationRouteWithChildren
  PlaygroundRoute: typeof PlaygroundRoute
  ProvidersRoute: typeof ProvidersRoute
  RoutingRoute: typeof RoutingRoute
  SettingsRoute: typeof SettingsRoute
  ToolsRoute: typeof ToolsRouteWithChildren
  UsageRoute: typeof UsageRoute
  WorkspacesRoute: typeof WorkspacesRoute
  AdminAccountsRoute: typeof AdminAccountsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aliases': {
      id: '/aliases'
      path: '/aliases'
      fullPath: '/aliases'
      preLoaderRoute: typeof AliasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets': {
      id: '/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof BudgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations': {
      id: '/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof InvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keys': {
      id: '/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof KeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routing': {
      id: '/routing'
      path: '/routing'
      fullPath: '/routing'
      preLoaderRoute: typeof RoutingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/accounts': {
      id: '/admin/accounts'
      path: '/admin/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/': {
      id: '/models/'
      path: '/'
      fullPath: '/models/'
      preLoaderRoute: typeof ModelsIndexRouteImport
      parentRoute: typeof ModelsRoute
    }
    '/models/$': {
      id: '/models/$'
      path: '/$'
      fullPath: '/models/$'
      preLoaderRoute: typeof ModelsSplatRouteImport
      parentRoute: typeof ModelsRoute
    }
    '/organization/': {
      id: '/organization/'
      path: '/'
      fullPath: '/organization/'
      preLoaderRoute: typeof OrganizationIndexRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/organization/domains': {
      id: '/organization/domains'
      path: '/domains'
      fullPath: '/organization/domains'
      preLoaderRoute: typeof OrganizationDomainsRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/organization/members': {
      id: '/organization/members'
      path: '/members'
      fullPath: '/organization/members'
      preLoaderRoute: typeof OrganizationMembersRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/organization/pricing': {
      id: '/organization/pricing'
      path: '/pricing'
      fullPath: '/organization/pricing'
      preLoaderRoute: typeof OrganizationPricingRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/organization/provider-keys': {
      id: '/organization/provider-keys'
      path: '/provider-keys'
      fullPath: '/organization/provider-keys'
      preLoaderRoute: typeof OrganizationProviderKeysRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/organization/usage': {
      id: '/organization/usage'
      path: '/usage'
      fullPath: '/organization/usage'
      preLoaderRoute: typeof OrganizationUsageRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/tools/': {
      id: '/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/code-execution': {
      id: '/tools/code-execution'
      path: '/code-execution'
      fullPath: '/tools/code-execution'
      preLoaderRoute: typeof ToolsCodeExecutionRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/mcp-servers': {
      id: '/tools/mcp-servers'
      path: '/mcp-servers'
      fullPath: '/tools/mcp-servers'
      preLoaderRoute: typeof ToolsMcpServersRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/web-search': {
      id: '/tools/web-search'
      path: '/web-search'
      fullPath: '/tools/web-search'
      preLoaderRoute: typeof ToolsWebSearchRouteImport
      parentRoute: typeof ToolsRoute
    }
  }
}

interface ModelsRouteChildren {
  ModelsSplatRoute: typeof ModelsSplatRoute
  ModelsIndexRoute: typeof ModelsIndexRoute
}

const ModelsRouteChildren: ModelsRouteChildren = {
  ModelsSplatRoute: ModelsSplatRoute,
  ModelsIndexRoute: ModelsIndexRoute,
}

const ModelsRouteWithChildren =
  ModelsRoute._addFileChildren(ModelsRouteChildren)

interface OrganizationRouteChildren {
  OrganizationDomainsRoute: typeof OrganizationDomainsRoute
  OrganizationMembersRoute: typeof OrganizationMembersRoute
  OrganizationPricingRoute: typeof OrganizationPricingRoute
  OrganizationProviderKeysRoute: typeof OrganizationProviderKeysRoute
  OrganizationUsageRoute: typeof OrganizationUsageRoute
  OrganizationIndexRoute: typeof OrganizationIndexRoute
}

const OrganizationRouteChildren: OrganizationRouteChildren = {
  OrganizationDomainsRoute: OrganizationDomainsRoute,
  OrganizationMembersRoute: OrganizationMembersRoute,
  OrganizationPricingRoute: OrganizationPricingRoute,
  OrganizationProviderKeysRoute: OrganizationProviderKeysRoute,
  OrganizationUsageRoute: OrganizationUsageRoute,
  OrganizationIndexRoute: OrganizationIndexRoute,
}

const OrganizationRouteWithChildren = OrganizationRoute._addFileChildren(
  OrganizationRouteChildren,
)

interface ToolsRouteChildren {
  ToolsCodeExecutionRoute: typeof ToolsCodeExecutionRoute
  ToolsMcpServersRoute: typeof ToolsMcpServersRoute
  ToolsWebSearchRoute: typeof ToolsWebSearchRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsCodeExecutionRoute: ToolsCodeExecutionRoute,
  ToolsMcpServersRoute: ToolsMcpServersRoute,
  ToolsWebSearchRoute: ToolsWebSearchRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AccountRoute: AccountRoute,
  ActivityRoute: ActivityRoute,
  AliasesRoute: AliasesRoute,
  BudgetsRoute: BudgetsRoute,
  DocsRoute: DocsRoute,
  InvitationsRoute: InvitationsRoute,
  KeysRoute: KeysRoute,
  MembersRoute: MembersRoute,
  ModelsRoute: ModelsRouteWithChildren,
  OrganizationRoute: OrganizationRouteWithChildren,
  PlaygroundRoute: PlaygroundRoute,
  ProvidersRoute: ProvidersRoute,
  RoutingRoute: RoutingRoute,
  SettingsRoute: SettingsRoute,
  ToolsRoute: ToolsRouteWithChildren,
  UsageRoute: UsageRoute,
  WorkspacesRoute: WorkspacesRoute,
  AdminAccountsRoute: AdminAccountsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
